pub mod screen_connection_handler;
pub mod screen_order_manager;
pub mod screen_order_parser;
pub mod screen_payment_system;
pub mod screen_to_robot_connection;
pub mod screen_to_robot_connector;
pub mod screen_working_order;
pub mod user_input;
pub mod screen_constants;